version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: noyon_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: noyon_db
    ports:
      - "3306:3306"
    restart: always