spring.application.name=Noyon

# Veritaban? Ba?lant? Ayarlar? (Güvenlik izni eklendi)
spring.datasource.url=jdbc:mysql://localhost:3306/noyon_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Tablolar? Otomatik Olu?turma Ayar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true